In [66]:
import numpy as np
M=np.array([[1,2,3],[4,5,6],[7,8,9]]);
V=(np.array([1,2,3])).reshape(3,1);
print("Size of M=",M.shape);
print("Size of V=",V.shape);
print("V+V=",np.add(V,V));
print("2*v=",np.dot(2,V));
Z=np.zeros((3,1),dtype=int);
print("Z=",Z);
print(np.eye(3,dtype=int));
print("M*v",M.dot(V));
print("Transpose of M=",M.T);
print("V.*V=",np.multiply(V,V));
print("Inverse of M=",(np.linalg.inv(M)));


Size of M= (3, 3)
Size of V= (3, 1)
V+V= [[2]
 [4]
 [6]]
2*v= [[2]
 [4]
 [6]]
Z= [[0]
 [0]
 [0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
M*v [[14]
 [32]
 [50]]
Transpose of M= [[1 4 7]
 [2 5 8]
 [3 6 9]]
V.*V= [[1]
 [4]
 [9]]
Inverse of M= [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
